version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    container_name: diploma_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./diploma_db_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      retries: 10
      interval: 3s

  api:
    build: . 
    env_file: .env
    environment: 
      DB_HOST: db
    depends_on:
      db: 
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
   diploma_db_data: