version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./diploma_db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 5
      interval: 3s

  api:
    build: .
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000  
    volumes:
      - ./todolist:/opt/todolist/
      - ./core:/opt/core/

  collectstatic:
    build: .
    env_file: .env
    entrypoint: ''
    volumes:
      - django_static:/opt/static
    command: python3 manage.py collectstatic -c --noinput
  
  frontend:
    image: sermalenk/skypro-front:lesson-35
    ports:
     - "80:80"
    depends_on:
      collectstatic:
        condition: service_completed_successfully
    volumes:
      - django_static:/usr/share/nginx/html/static
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  diploma_db_data:
  django_static:
